steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-west2-docker.pkg.dev/primeval-gear-472313-v7/la-megacity/la-megacity-dashboard:latest'
  - '.'
images:
- 'us-west2-docker.pkg.dev/primeval-gear-472313-v7/la-megacity/la-megacity-dashboard:latest'
options:
  logging: CLOUD_LOGGING_ONLY
