steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/la-megacity/la-megacity-dashboard:$COMMIT_SHA', '.']
# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west2-docker.pkg.dev/$PROJECT_ID/la-megacity/la-megacity-dashboard:$COMMIT_SHA']
# 3. Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'la-megacity-dashboard'
    - '--image=us-west2-docker.pkg.dev/$PROJECT_ID/la-megacity/la-megacity-dashboard:$COMMIT_SHA'
    - '--region=us-west2'
    - '--platform=managed'
    - '--allow-unauthenticated'
    # Use the actual service account email instead of the shell command
    - '--service-account=826691286079-compute@developer.gserviceaccount.com'
# This option increases the default build timeout to prevent timing out on complex builds.
timeout: '1200s'
# Add this entire section to your file
options:
  logging: CLOUD_LOGGING_ONLY
